use Portfolio

insert into Employers
values (1, 'Adssets', '2014-06-02', '2016-05-04'),
	   (2, 'Cybercom', '2016-05-04', '2016-08-08'),
	   (3, 'SVRVIVE Studios', '2016-08-08', '2018-03-14'),
	   (4, 'Sopra Steria', '2018-03-14', NULL);

insert into Projects
values (1, 'C&C Red Alert 3 - Resurrection (Mod)', 'Music producer', '', 2, '2009-07-01', '2010-04-01', 0, 0, 'Team Vikestart', NULL),
	   (2, 'Adsscore', 'Java Developer', '', 1, '2014-06-02', '2016-05-04', 0, 1, NULL, 1),
	   (3, 'Systems administration', 'Systems Administrator', '', 1, '2014-07-15', '2016-05-04', 0, 1, NULL, 1),
	   (4, 'Data gatherer', 'Java Developer', '', 1, '2014-09-15', '2016-05-04', 0, 1, NULL, 1),
	   (5, 'MetroMaze (Global Gamejam 2016)', 'Defold Developer', '', 2, '2016-01-29', '2016-01-31', 0, 1, NULL, NULL),
	   (6, 'Cards and Loans', 'Java Consultant', '', 1, '2016-05-10', '2016-08-08', 0, 1, 'CrossKey', 2),
	   (7, 'SVRVIVE - The Deus Helix', 'Unity Developer', '', 1, '2016-08-08', '2017-09-15', 0, 1, NULL, 3),
	   (8, 'ZpazeWavez', 'Sound programmer & music producer', '', 2, '2017-01-20', '2017-01-22', 0, 1, NULL, NULL),
	   (9, 'Kartong - Death By Cardboard!', 'AWS Developer', '', 1, '2017-09-01', '2018-03-14', 0, 1, NULL, 3),
	   (10, 'CLASSIFIED PROJECT', 'Unity Developer & Producer', '', 1, '2017-06-05', '2017-10-10', 0, 1, NULL, 3),
	   (11, 'Krystal Kart AR', 'NodeJS Developer', '', 1, '2018-02-10', '2018-03-14', 0, 1, NULL, 3),
	   (12, 'Kammarkollegiets Tolkavropstjänst', 'Full-stack .NET Developer', '', 1, '2018-06-15', '2019-04-11', 1, 1, 'Kammarkollegiet', 4),
	   (13, 'Autonomous Stock Analysis Tool', 'Python Developer', '', 2, '2019-01-15', '2019-08-15', 0, 1, NULL, NULL),
	   (14, 'CLASSIFIED PROJECT', '.NET Developer', '', 1, '2019-04-11', '2019-06-27', 0, 1, 'Rovio Entertainment Corporation', 4),
	   (15, 'Smidas', '.NET Developer', '', 2, '2019-09-15', '2019-12-10', 1, 1, NULL, NULL),
	   (16, 'Dental Care Systems', 'Full-stack .NET Developer', '', 1, '2019-07-15', NULL, 0, 1, 'Tandvårdsenheten Region Västmanland & Region Dalarna', 4),
	   (17, 'Libretto 2.0', 'Full-stack .NET Developer', '', 1, '2020-03-01', '2020-08-14', 0, 1, 'Tandvårdsenheten Region Stockholm', 4);

insert into Technologies
values (1, 'Java EE'),
	   (2, 'Linux'),
	   (3, 'HTML'),
	   (4, 'CSS'),
	   (5, 'MySQL'),
	   (6, 'GlassFish'),
	   (7, 'Ubuntu'),
	   (8, 'Bash'),
	   (9, 'SSH'),
	   (10, 'JavaScript'),
	   (11, 'AJAX'),
	   (12, 'Atlassian Jira'),
	   (13, 'EJB (Enterprise JavaBeans)'),
	   (14, 'Git'),
	   (15, 'GitHub'),
	   (16, 'JDBC'),
	   (17, 'jQuery'),
	   (18, 'JSON'),
	   (19, 'SQL'),
	   (20, 'Shell script'),
	   (21, 'Python'),
	   (22, 'NGINX'),
	   (23, 'Backup & restore'),
	   (24, 'Cron'),
	   (25, 'Defold Engine'),
	   (26, 'Lua'),
	   (27, 'Game design'),
	   (28, 'JUnit'),
	   (29, 'Oracle Database'),
	   (30, 'SVN'),
	   (31, 'Selenium'),
	   (32, 'Scrum'),
	   (33, 'Automated UI testing'),
	   (34, 'Jenkins'),
	   (35, 'Agile development'),
	   (36, 'C#'),
	   (37, 'FMOD'),
	   (38, 'Git LFS'),
	   (39, 'GitLab'),
	   (40, 'HTC Vive'),
	   (41, 'NewtonVR'),
	   (42, 'Oculus Rift'),
	   (43, 'Prototyping'),
	   (44, 'Sourcetree'),
	   (45, 'SteamVR'),
	   (46, 'Steamworks'),
	   (47, 'Unity3D'),
	   (48, 'Viveport'),
	   (49, 'Virtual Reality'),
	   (50, 'FL Studio'),
	   (51, 'Project management'),
	   (52, 'VRTK'),
	   (53, 'Amazon Web Services (AWS)'),
	   (54, 'REST API'),
	   (55, 'Unit testing'),
	   (56, 'Batch script'),
	   (57, 'Chai.js'),
	   (58, 'Database modeling'),
	   (59, 'Mocha'),
	   (60, 'Test Driven Development (TDD)'),
	   (61, 'Node.js'),
	   (62, '.NET Core'),
	   (63, 'Atlassian Confluence'),
	   (64, 'Bootstrap'),
	   (65, 'Entity Framework (EF)'),
	   (66, 'FluentAssertions'),
	   (67, 'GitExtensions'),
	   (68, 'gulp.js'),
	   (69, 'Less'),
	   (70, 'LINQ'),
	   (71, 'Microsoft Visual Studio'),
	   (72, 'Model-view-controller (MVC)'),
	   (73, 'Razor (HTML5)'),
	   (74, 'Regular expressions'),
	   (75, 'SQL Server'),
	   (76, 'T-SQL'),
	   (77, 'Unified Modeling Language (UML)'),
	   (78, 'xUnit'),
	   (79, 'Stocks'),
	   (80, 'Stock analysis'),
	   (81, 'Pycharm'),
	   (82, 'Synology'),
	   (83, 'Synology DSM'),
	   (84, 'Value investment'),
	   (85, 'XPath'),
	   (86, 'FakeItEasy'),
	   (87, 'HashiCorp Terraform'),
	   (88, 'Infrastructure as Code (IaC)'),
	   (89, 'OS X'),
	   (90, 'PostgreSQL'),
	   (91, 'React.js'),
	   (92, 'Rider'),
	   (93, 'TeamCity'),
	   (94, 'Unix'),
	   (95, 'Azure Functions'),
	   (96, 'curl'),
	   (97, 'Microsoft Excel'),
	   (98, '.NET Framework'),
	   (99, 'WebForms'),
	   (100, 'Azure DevOps'),
	   (101, 'React Router'),
	   (102, 'TypeScript'),
	   (103, 'React Hooks');

insert into ProjectTechnologies
values (1, 2, (SELECT Id FROM Technologies WHERE Name = 'Java EE')),
	   (2, 2, (SELECT Id FROM Technologies WHERE Name = 'HTML')),
	   (3, 2, (SELECT Id FROM Technologies WHERE Name = 'CSS')),
	   (4, 2, (SELECT Id FROM Technologies WHERE Name = 'MySQL')),
	   (5, 2, (SELECT Id FROM Technologies WHERE Name = 'GlassFish')),
	   (6, 2, (SELECT Id FROM Technologies WHERE Name = 'Ubuntu')),
	   (7, 2, (SELECT Id FROM Technologies WHERE Name = 'Bash')),
	   (8, 2, (SELECT Id FROM Technologies WHERE Name = 'SSH')),
	   (9, 2, (SELECT Id FROM Technologies WHERE Name = 'JavaScript')),
	   (10, 2, (SELECT Id FROM Technologies WHERE Name = 'AJAX')),
	   (11, 2, (SELECT Id FROM Technologies WHERE Name = 'Atlassian Jira')),
	   (12, 2, (SELECT Id FROM Technologies WHERE Name = 'EJB (Enterprise JavaBeans)')),
	   (13, 2, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (14, 2, (SELECT Id FROM Technologies WHERE Name = 'GitHub')),
	   (15, 2, (SELECT Id FROM Technologies WHERE Name = 'JDBC')),
	   (16, 2, (SELECT Id FROM Technologies WHERE Name = 'jQuery')),
	   (17, 2, (SELECT Id FROM Technologies WHERE Name = 'JSON')),
	   (18, 2, (SELECT Id FROM Technologies WHERE Name = 'SQL')),
	   (19, 3, (SELECT Id FROM Technologies WHERE Name = 'Linux')),
	   (20, 3, (SELECT Id FROM Technologies WHERE Name = 'Ubuntu')),
	   (21, 3, (SELECT Id FROM Technologies WHERE Name = 'MySQL')),
	   (22, 3, (SELECT Id FROM Technologies WHERE Name = 'Shell script')),
	   (23, 3, (SELECT Id FROM Technologies WHERE Name = 'Bash')),
	   (24, 3, (SELECT Id FROM Technologies WHERE Name = 'Python')),
	   (25, 3, (SELECT Id FROM Technologies WHERE Name = 'GlassFish')),
	   (26, 3, (SELECT Id FROM Technologies WHERE Name = 'NGINX')),
	   (27, 3, (SELECT Id FROM Technologies WHERE Name = 'Backup & restore')),
	   (28, 3, (SELECT Id FROM Technologies WHERE Name = 'Cron')),
	   (29, 3, (SELECT Id FROM Technologies WHERE Name = 'Atlassian Jira')),
	   (30, 4, (SELECT Id FROM Technologies WHERE Name = 'Bash')),
	   (31, 4, (SELECT Id FROM Technologies WHERE Name = 'EJB (Enterprise JavaBeans')),
	   (32, 4, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (33, 4, (SELECT Id FROM Technologies WHERE Name = 'GlassFish')),
	   (34, 4, (SELECT Id FROM Technologies WHERE Name = 'JDBC')),
	   (35, 4, (SELECT Id FROM Technologies WHERE Name = 'Java EE')),
	   (36, 4, (SELECT Id FROM Technologies WHERE Name = 'MySQL')),
	   (37, 4, (SELECT Id FROM Technologies WHERE Name = 'SQL')),
	   (38, 4, (SELECT Id FROM Technologies WHERE Name = 'Ubuntu')),
	   (39, 5, (SELECT Id FROM Technologies WHERE Name = 'Defold Engine')),
	   (40, 5, (SELECT Id FROM Technologies WHERE Name = 'Lua')),
	   (41, 5, (SELECT Id FROM Technologies WHERE Name = 'Game design')),
	   (42, 6, (SELECT Id FROM Technologies WHERE Name = 'JUnit')),
	   (43, 6, (SELECT Id FROM Technologies WHERE Name = 'Java EE')),
	   (44, 6, (SELECT Id FROM Technologies WHERE Name = 'Oracle Database')),
	   (45, 6, (SELECT Id FROM Technologies WHERE Name = 'SVN')),
	   (46, 6, (SELECT Id FROM Technologies WHERE Name = 'Selenium')),
	   (47, 6, (SELECT Id FROM Technologies WHERE Name = 'Scrum')),
	   (48, 6, (SELECT Id FROM Technologies WHERE Name = 'Automated UI testing')),
	   (49, 6, (SELECT Id FROM Technologies WHERE Name = 'Jenkins')),
	   (50, 7, (SELECT Id FROM Technologies WHERE Name = 'Agile development')),
	   (51, 7, (SELECT Id FROM Technologies WHERE Name = 'C#')),
	   (52, 7, (SELECT Id FROM Technologies WHERE Name = 'FMOD')),
	   (53, 7, (SELECT Id FROM Technologies WHERE Name = 'Game design')),
	   (54, 7, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (55, 7, (SELECT Id FROM Technologies WHERE Name = 'Git LFS')),
	   (56, 7, (SELECT Id FROM Technologies WHERE Name = 'GitLab')),
	   (57, 7, (SELECT Id FROM Technologies WHERE Name = 'HTC Vive')),
	   (58, 7, (SELECT Id FROM Technologies WHERE Name = 'NewtonVR')),
	   (59, 7, (SELECT Id FROM Technologies WHERE Name = 'Oculus Rift')),
	   (60, 7, (SELECT Id FROM Technologies WHERE Name = 'Prototyping')),
	   (61, 7, (SELECT Id FROM Technologies WHERE Name = 'Scrum')),
	   (62, 7, (SELECT Id FROM Technologies WHERE Name = 'Sourcetree')),
	   (63, 7, (SELECT Id FROM Technologies WHERE Name = 'SteamVR')),
	   (64, 7, (SELECT Id FROM Technologies WHERE Name = 'Steamworks')),
	   (65, 7, (SELECT Id FROM Technologies WHERE Name = 'Unity3D')),
	   (66, 7, (SELECT Id FROM Technologies WHERE Name = 'Viveport')),
	   (67, 7, (SELECT Id FROM Technologies WHERE Name = 'Virtual Reality')),
	   (68, 8, (SELECT Id FROM Technologies WHERE Name = 'Unity3D')),
	   (69, 8, (SELECT Id FROM Technologies WHERE Name = 'C#')),
	   (70, 8, (SELECT Id FROM Technologies WHERE Name = 'FL Studio')),
	   (71, 8, (SELECT Id FROM Technologies WHERE Name = 'FMOD')),
	   (72, 8, (SELECT Id FROM Technologies WHERE Name = 'Game design')),
	   (73, 9, (SELECT Id FROM Technologies WHERE Name = 'C#')),
	   (74, 9, (SELECT Id FROM Technologies WHERE Name = 'Game design')),
	   (75, 9, (SELECT Id FROM Technologies WHERE Name = 'HTC Vive')),
	   (76, 9, (SELECT Id FROM Technologies WHERE Name = 'Oculus Rift')),
	   (77, 9, (SELECT Id FROM Technologies WHERE Name = 'Project management')),
	   (78, 9, (SELECT Id FROM Technologies WHERE Name = 'Prototyping')),
	   (79, 9, (SELECT Id FROM Technologies WHERE Name = 'Unity3D')),
	   (80, 9, (SELECT Id FROM Technologies WHERE Name = 'VRTK')),
	   (81, 9, (SELECT Id FROM Technologies WHERE Name = 'Virtual Reality')),
	   (82, 10, (SELECT Id FROM Technologies WHERE Name = 'Agile development')),
	   (83, 10, (SELECT Id FROM Technologies WHERE Name = 'Amazon Web Services (AWS)')),
	   (84, 10, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (85, 10, (SELECT Id FROM Technologies WHERE Name = 'Git LFS')),
	   (86, 10, (SELECT Id FROM Technologies WHERE Name = 'GitLab')),
	   (87, 10, (SELECT Id FROM Technologies WHERE Name = 'REST API')),
	   (88, 10, (SELECT Id FROM Technologies WHERE Name = 'Scrum')),
	   (89, 10, (SELECT Id FROM Technologies WHERE Name = 'Sourcetree')),
	   (90, 10, (SELECT Id FROM Technologies WHERE Name = 'Virtual Reality')),
	   (91, 11, (SELECT Id FROM Technologies WHERE Name = 'Amazon Web Services (AWS)')),
	   (92, 11, (SELECT Id FROM Technologies WHERE Name = 'Unit testing')),
	   (93, 11, (SELECT Id FROM Technologies WHERE Name = 'Batch script')),
	   (94, 11, (SELECT Id FROM Technologies WHERE Name = 'Chai.js')),
	   (95, 11, (SELECT Id FROM Technologies WHERE Name = 'Database modeling')),
	   (96, 11, (SELECT Id FROM Technologies WHERE Name = 'JSON')),
	   (97, 11, (SELECT Id FROM Technologies WHERE Name = 'Mocha')),
	   (98, 11, (SELECT Id FROM Technologies WHERE Name = 'MySQL')),
	   (99, 11, (SELECT Id FROM Technologies WHERE Name = 'Node.js')),
	   (100, 11, (SELECT Id FROM Technologies WHERE Name = 'SQL')),
	   (101, 11, (SELECT Id FROM Technologies WHERE Name = 'Test Driven Development (TDD)')),
	   (102, 12, (SELECT Id FROM Technologies WHERE Name = '.NET Core')),
	   (103, 12, (SELECT Id FROM Technologies WHERE Name = 'AJAX')),
	   (104, 12, (SELECT Id FROM Technologies WHERE Name = 'Atlassian Jira')),
	   (105, 12, (SELECT Id FROM Technologies WHERE Name = 'Atlassian Confluence')),
	   (106, 12, (SELECT Id FROM Technologies WHERE Name = 'Bootstrap')),
	   (107, 12, (SELECT Id FROM Technologies WHERE Name = 'C#')),
	   (108, 12, (SELECT Id FROM Technologies WHERE Name = 'CSS')),
	   (109, 12, (SELECT Id FROM Technologies WHERE Name = 'Unit testing')),
	   (110, 12, (SELECT Id FROM Technologies WHERE Name = 'Entity Framework (EF)')),
	   (111, 12, (SELECT Id FROM Technologies WHERE Name = 'FluentAssertions')),
	   (112, 12, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (113, 12, (SELECT Id FROM Technologies WHERE Name = 'GitExtensions')),
	   (114, 12, (SELECT Id FROM Technologies WHERE Name = 'HTML')),
	   (115, 12, (SELECT Id FROM Technologies WHERE Name = 'gulp.js')),
	   (116, 12, (SELECT Id FROM Technologies WHERE Name = 'JavaScript')),
	   (117, 12, (SELECT Id FROM Technologies WHERE Name = 'jQuery')),
	   (118, 12, (SELECT Id FROM Technologies WHERE Name = 'Less')),
	   (119, 12, (SELECT Id FROM Technologies WHERE Name = 'LINQ')),
	   (120, 12, (SELECT Id FROM Technologies WHERE Name = 'Microsoft Visual Studio')),
	   (121, 12, (SELECT Id FROM Technologies WHERE Name = 'Model-view-controller (MVC)')),
	   (122, 12, (SELECT Id FROM Technologies WHERE Name = 'Razor (HTML5)')),
	   (123, 12, (SELECT Id FROM Technologies WHERE Name = 'Regular expressions')),
	   (124, 12, (SELECT Id FROM Technologies WHERE Name = 'SQL Server')),
	   (125, 12, (SELECT Id FROM Technologies WHERE Name = 'T-SQL')),
	   (126, 12, (SELECT Id FROM Technologies WHERE Name = 'Unified Modeling Language (UML)')),
	   (127, 12, (SELECT Id FROM Technologies WHERE Name = 'xUnit')),
	   (128, 13, (SELECT Id FROM Technologies WHERE Name = 'Stocks')),
	   (129, 13, (SELECT Id FROM Technologies WHERE Name = 'Stock analysis')),
	   (130, 13, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (131, 13, (SELECT Id FROM Technologies WHERE Name = 'GitHub')),
	   (132, 13, (SELECT Id FROM Technologies WHERE Name = 'Linux')),
	   (133, 13, (SELECT Id FROM Technologies WHERE Name = 'Pycharm')),
	   (134, 13, (SELECT Id FROM Technologies WHERE Name = 'Python')),
	   (135, 13, (SELECT Id FROM Technologies WHERE Name = 'Regular expressions')),
	   (136, 13, (SELECT Id FROM Technologies WHERE Name = 'Selenium')),
	   (137, 13, (SELECT Id FROM Technologies WHERE Name = 'Synology')),
	   (138, 13, (SELECT Id FROM Technologies WHERE Name = 'Synology DSM')),
	   (139, 13, (SELECT Id FROM Technologies WHERE Name = 'Test Driven Development (TDD)')),
	   (140, 13, (SELECT Id FROM Technologies WHERE Name = 'Value investment')),
	   (141, 13, (SELECT Id FROM Technologies WHERE Name = 'Unified Modeling Language (UML)')),
	   (142, 13, (SELECT Id FROM Technologies WHERE Name = 'XPath')),
	   (143, 14, (SELECT Id FROM Technologies WHERE Name = '.NET Core')),
	   (144, 14, (SELECT Id FROM Technologies WHERE Name = 'Amazon Web Services (AWS)')),
	   (145, 14, (SELECT Id FROM Technologies WHERE Name = 'Bash')),
	   (146, 14, (SELECT Id FROM Technologies WHERE Name = 'C#')),
	   (147, 14, (SELECT Id FROM Technologies WHERE Name = 'Unit testing')),
	   (148, 14, (SELECT Id FROM Technologies WHERE Name = 'FakeItEasy')),
	   (149, 14, (SELECT Id FROM Technologies WHERE Name = 'FluentAssertions')),
	   (150, 14, (SELECT Id FROM Technologies WHERE Name = 'HashiCorp Terraform')),
	   (151, 14, (SELECT Id FROM Technologies WHERE Name = 'Infrastructure as Code (IaC)')),
	   (152, 14, (SELECT Id FROM Technologies WHERE Name = 'JavaScript')),
	   (153, 14, (SELECT Id FROM Technologies WHERE Name = 'Linux')),
	   (154, 14, (SELECT Id FROM Technologies WHERE Name = 'Node.js')),
	   (155, 14, (SELECT Id FROM Technologies WHERE Name = 'OS X')),
	   (156, 14, (SELECT Id FROM Technologies WHERE Name = 'PostgreSQL')),
	   (157, 14, (SELECT Id FROM Technologies WHERE Name = 'React.js')),
	   (158, 14, (SELECT Id FROM Technologies WHERE Name = 'Shell script')),
	   (159, 14, (SELECT Id FROM Technologies WHERE Name = 'Rider')),
	   (160, 14, (SELECT Id FROM Technologies WHERE Name = 'TeamCity')),
	   (161, 14, (SELECT Id FROM Technologies WHERE Name = 'Test Driven Development (TDD)')),
	   (162, 14, (SELECT Id FROM Technologies WHERE Name = 'Ubuntu')),
	   (163, 14, (SELECT Id FROM Technologies WHERE Name = 'Unity3D')),
	   (164, 14, (SELECT Id FROM Technologies WHERE Name = 'Unix')),
	   (165, 14, (SELECT Id FROM Technologies WHERE Name = 'xUnit')),
	   (166, 15, (SELECT Id FROM Technologies WHERE Name = '.NET Core')),
	   (167, 15, (SELECT Id FROM Technologies WHERE Name = 'Stocks')),
	   (168, 15, (SELECT Id FROM Technologies WHERE Name = 'Stock analysis')),
	   (169, 15, (SELECT Id FROM Technologies WHERE Name = 'Azure Functions')),
	   (179, 15, (SELECT Id FROM Technologies WHERE Name = 'curl')),
	   (180, 15, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (181, 15, (SELECT Id FROM Technologies WHERE Name = 'GitHub')),
	   (182, 15, (SELECT Id FROM Technologies WHERE Name = 'Microsoft Excel')),
	   (183, 15, (SELECT Id FROM Technologies WHERE Name = 'Regular expressions')),
	   (184, 15, (SELECT Id FROM Technologies WHERE Name = 'Value investment')),
	   (185, 15, (SELECT Id FROM Technologies WHERE Name = 'XPath')),
	   (186, 16, (SELECT Id FROM Technologies WHERE Name = '.NET Framework')),
	   (187, 16, (SELECT Id FROM Technologies WHERE Name = 'Azure DevOps')),
	   (188, 16, (SELECT Id FROM Technologies WHERE Name = 'Batch script')),
	   (189, 16, (SELECT Id FROM Technologies WHERE Name = 'Unit testing')),
	   (190, 16, (SELECT Id FROM Technologies WHERE Name = 'FakeItEasy')),
	   (191, 16, (SELECT Id FROM Technologies WHERE Name = 'Microsoft Visual Studio')),
	   (192, 16, (SELECT Id FROM Technologies WHERE Name = 'SQL Server')),
	   (193, 16, (SELECT Id FROM Technologies WHERE Name = 'T-SQL')),
	   (194, 16, (SELECT Id FROM Technologies WHERE Name = 'xUnit')),
	   (195, 17, (SELECT Id FROM Technologies WHERE Name = '.NET Core')),
	   (196, 17, (SELECT Id FROM Technologies WHERE Name = 'Azure DevOps')),
	   (197, 17, (SELECT Id FROM Technologies WHERE Name = 'C#')),
	   (198, 17, (SELECT Id FROM Technologies WHERE Name = 'Git')),
	   (199, 17, (SELECT Id FROM Technologies WHERE Name = 'GitExtensions')),
	   (200, 17, (SELECT Id FROM Technologies WHERE Name = 'React Hooks')),
	   (201, 17, (SELECT Id FROM Technologies WHERE Name = 'React Router')),
	   (202, 17, (SELECT Id FROM Technologies WHERE Name = 'Scrum')),
	   (203, 17, (SELECT Id FROM Technologies WHERE Name = 'SQL Server')),
	   (204, 17, (SELECT Id FROM Technologies WHERE Name = 'TypeScript')),
	   (205, 17, (SELECT Id FROM Technologies WHERE Name = 'Entity Framework (EF)')),
	   (206, 17, (SELECT Id FROM Technologies WHERE Name = 'T-SQL'));
