// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Portfolio.Core;

namespace Portfolio.Core.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20201014154915_UpdateCopyTacks")]
    partial class UpdateCopyTacks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Portfolio.Core.Entities.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("EmployerDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Employers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployerDescription = "Adssets is a small company that creates and serves rich-media advertisements on web publications.",
                            EndDate = new DateTime(2016, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adssets",
                            RoleDescription = "With this employment, Dennis was thrust into the programming world with a bang. Due to the company's small size, Dennis seized the opportunity to get busy working with several apps, as well as the server infrastructure that ran the apps.",
                            StartDate = new DateTime(2014, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            EmployerDescription = "Cybercom Group is a swedish IT-consultancy firm.",
                            EndDate = new DateTime(2016, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cybercom Group",
                            RoleDescription = "Dennis was briefly assigned to CrossKey as a Java consultant, where he helped the Cards and Loans team develop new functionality and create regression tests with Selenium, to ensure web-flows work as intended.",
                            StartDate = new DateTime(2016, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            EmployerDescription = "SVRVIVE Studios (now Antler Interactive) is a small game studio which was initially focused on VR gaming. The studio has created games like SVRVIVE - The Deus Helix, Kartong - Death By Cardboard! and Krystal Kart AR.",
                            EndDate = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "SVRVIVE Studios",
                            RoleDescription = "As a VR-developer, Dennis helped finish and release SVRVIVE Studios first game (SVRVIVE - The Deus Helix) and helped bring the game to the chinese markets through Viveport. Additionally, since the company was so small, Dennis took the opportunity to handle much of the studios IT-infrastructure and also tried a short tenure as a producer for an unreleased game.",
                            StartDate = new DateTime(2016, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            EmployerDescription = "Sopra Steria is a large multi-national IT-consultancy firm based in France.",
                            Name = "Sopra Steria",
                            RoleDescription = "As a full-stack .NET consultant, Dennis has been involved in several projects, both in-house and on-site, for customers like Kammarkollegiet, Rovio Entertainment (famous for Angry Birds) and Tandvårdsförvaltningen Region Stockholm, Region Västmanland and Region Dalarna. Dennis has also done lectures for Sopra Sterias graduates within Unity3D programming, and Test Driven Development (TDD).",
                            StartDate = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Customer")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Show")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Customer = "Team Vikestart",
                            Description = "",
                            EndDate = new DateTime(2010, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "C&C Red Alert 3 - Resurrection (Mod)",
                            Role = "Music producer",
                            Show = false,
                            StartDate = new DateTime(2009, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Description = "Adsscore is an internal statistics system geared towards professional clients. Through this system the clients could view their Adssets advert's results. As a Java developer Dennis developed new features and maintained the system. He also helped improve the apps performance through quicker response times, which improved the client's user experience. Dennis also maintained the application's infrastructure, namely web servers, application servers and database servers.",
                            EmployerId = 1,
                            EndDate = new DateTime(2016, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Adsscore",
                            Role = "Java Developer",
                            Show = true,
                            StartDate = new DateTime(2014, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            Description = "",
                            EmployerId = 1,
                            EndDate = new DateTime(2016, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Systems administration",
                            Role = "Systems Administrator",
                            Show = false,
                            StartDate = new DateTime(2014, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "Data gatherer was an application that took raw advertising data from a bunch of servers and then compiled the data for presentation in Adsscore. Above all Dennis contributed with performance improvements as a Java developer and ensured the app could compile more data faster.",
                            EmployerId = 1,
                            EndDate = new DateTime(2016, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Data gatherer",
                            Role = "Java Developer",
                            Show = true,
                            StartDate = new DateTime(2014, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            Description = "MetroMaze is a top-down 2D RPG created during Global Game Jam 2016. In accordance with the theme \"Ritual\", you are a teenager chosen to complete the MetroMaze as your coming of age ritual, solve puzzles and uncover its mysteries. It was made using King's (then beta) game engine Defold. As a developer Dennis created most of the games base functionality in Lua: movement, interaction, text boxes, as well as the logic around graphics, sound and music.",
                            EndDate = new DateTime(2016, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "MetroMaze (Global Gamejam 2016)",
                            Role = "Defold Developer",
                            Show = true,
                            StartDate = new DateTime(2016, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Customer = "CrossKey",
                            Description = "Cards and Loans is a part of the Internet banking system that concerns application and management of debit and credit cards, and different type of bank loans. As java developer Dennis developed new features and bug-fixes for the Internet banking software. He also helped the company to increase its regression testing coverage in JUnit, which improved the app's stability.",
                            EmployerId = 2,
                            EndDate = new DateTime(2016, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Cards and Loans",
                            Role = "Java Consultant",
                            Show = true,
                            StartDate = new DateTime(2016, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Description = "SVRVIVE - The Deus Helix is the first game from SVRVIVE Studios made in Unity3D. You are Agent Null, an abducted human being who's been hired by aliens to search for pieces of the Deus Helix (the DNA of the universe) on exotic planets. As VR developer, Dennis developed gaming mechanics and puzzles in the game. Dennis was mainly responsible for integrating the game towards SteamVR and Viveport, as well as developing the game's checkpoints, saving and loading and VR menus. He also developed an internal localization solution and implemented it in the game, which meant that the company could translate the game to Chinese for the chinese Viveport market. This localization system also allows people to easily translate several languages and select language in the menu.",
                            EmployerId = 3,
                            EndDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "SVRVIVE - The Deus Helix",
                            Role = "Unity Developer",
                            Show = true,
                            StartDate = new DateTime(2016, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Description = "ZpazeWavez was a vertical scrolling shoot-ém-up made for Global Game Jam 2017. The game was created within 48 hours and plays much like Ikaruga, where you must match your plasma weapons color with the enemy's color. As sound programmer, Dennis implemented sound in the game with FMOD, an external sound engine for Unity3D. Dennis contributed with basic dynamics for the sound, for example minor changes in pitch in repeating sounds, making them sound more natural.",
                            EndDate = new DateTime(2017, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "ZpazeWavez",
                            Role = "Sound programmer & music producer",
                            Show = true,
                            StartDate = new DateTime(2017, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Description = "Kartong - Death By Cardboard! is a game created in Unreal Engine 4. You run in a procedurally generated mini maze made of cardboard. Your mission is to avoid traps and crazy, dangerous, and creepy toy experiments in order to get yourself to the mazes exit. The developers that worked on this game asked Dennis of a content delivery system for external partners that the company was talking to. They needed to store images and information on these people on a server outside of the game, and be able to programmatically reach these files from the client-side. Dennis created a simple REST-API on Amazon Web Services, where API Gateway mapped directly against objects in an S3 bucket. Thus the developers could easily load images and JSON-files to this bucket, download these files on-the-fly and use them in-game.",
                            EmployerId = 3,
                            EndDate = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Kartong - Death By Cardboard!",
                            Role = "AWS Developer",
                            Show = true,
                            StartDate = new DateTime(2017, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Description = "Anonymous VR game project. As a VR developer and producer, Dennis initally setup the project; he ensured that VRTK was installed, that all VR platforms were configured and worked. He also ensured that you could load and unload levels without disrupting user experience. As producer Dennis was responsible for the projects pre-production. Dennis ensured all key-people in all areas of expertise (art, game design, programming, sound & QA) drew up plans, planned and held meetings, helped when help was needed and reported to management upstairs.",
                            EmployerId = 3,
                            EndDate = new DateTime(2017, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "CLASSIFIED PROJECT",
                            Role = "Unity Developer & Producer",
                            Show = true,
                            StartDate = new DateTime(2017, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Description = "SVRVIVE Studios needed a first revision of a backend API for its client-side. The game was based on asynchronous multiplayer, and therefore needed a central API that handled player data. As a NodeJS developer, Dennis recieved the requirements from the developer responsible for the application. Together they defined what data the game needed to store, so Dennis could model and generate the database in MySQL Workbench, and then setup the environment on Amazon Web Services (API Gateway, Lambda & RDBS). After he created the first tests and functions he pushed on with the project. In the end the client could send requests to the server without issues.",
                            EmployerId = 3,
                            EndDate = new DateTime(2018, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Krystal Kart AR",
                            Role = "NodeJS Developer",
                            Show = true,
                            StartDate = new DateTime(2018, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Customer = "Kammarkollegiet",
                            Description = "A public-sector service for ordering interpretation services. The service is available to Swedish authorities, under the responsibility of the Chamber of Commerce. As a .NET developer, Dennis creates the remaining functionality required to get the first partial delivery of the service through the door. With a focus on what is required in the present, Dennis took on the tasks in the assignment and solved the tasks one by one.",
                            EmployerId = 4,
                            EndDate = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = true,
                            Name = "Kammarkollegiets Tolkavropstjänst",
                            Role = "Full-stack .NET Developer",
                            Show = true,
                            StartDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Description = "A private tool for performing technical analyses on entire stock indexes. The analysis is based on a value investment strategy and was run each weekday from Dennis' private server.",
                            EndDate = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Autonomous Stock Analysis Tool",
                            Role = "Python Developer",
                            Show = true,
                            StartDate = new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            Customer = "Rovio Entertainment Corporation",
                            Description = "Dennis was brought into this assignment to substitute a senior DevOps who went on parental leave. Since this role included multiple areas of responsibility, Dennis got to handle and build out the build servers, the cloud infrastructure, as well as the admin tooling for an ongoing game project. After that he helped develop the server application on which the game relied on. In order to bring the project to its next phase, a migration of the server application to virtual servers was necessary. Dennis performed this migration so the project could proceed. Thereafter he helped with improvements of the infrastructure and futher development of the codebase.",
                            EmployerId = 4,
                            EndDate = new DateTime(2019, 6, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "CLASSIFIED PROJECT",
                            Role = ".NET Developer",
                            Show = true,
                            StartDate = new DateTime(2019, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            Description = "Rewrite of the autonomous stock analysis tool to .NET Core and Azure Functions. The solution is hosted on the Azure cloud service and gets called by Dennis' home server through HTTPS. When the service registers the call it performs a technical analysis outlined by post data in JSON format and delivers an excel file which the server stores for later analysis.",
                            EndDate = new DateTime(2019, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = true,
                            Name = "Smidas",
                            Role = ".NET Developer",
                            Show = true,
                            StartDate = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            Customer = "Tandvårdsenheten Region Västmanland & Region Dalarna",
                            Description = "Making modifications to existing dental care systems, and getting them ready to release for Region Västmanland and Region Dalarna.",
                            EmployerId = 4,
                            IsHighlighted = false,
                            Name = "Dental Care Systems",
                            Role = "Full-stack .NET Developer",
                            Show = true,
                            StartDate = new DateTime(2019, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Customer = "Tandvårdsenheten Region Stockholm",
                            Description = "New version of an existing application, which focuses on a better user experience and better performance.",
                            EmployerId = 4,
                            EndDate = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = false,
                            Name = "Libretto 2.0",
                            Role = "Full-stack .NET Developer",
                            Show = true,
                            StartDate = new DateTime(2020, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            Description = @"Dennis realized his old WiX-portfolio wasn't up to task, so he built a personal portfolio CMS from scratch in .NET Core.

You're currently looking at the results in your browser. It's a dockerized Blazor Server website that runs on a virtual server that talks to a Postgres database cluster on DigitalOcean.
This page is overengineered to showcase Dennis' skills. He's also planning on setting up a backoffice for easier content management.

The source code is available on GitHub.",
                            EndDate = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsHighlighted = true,
                            Name = "Personal portfolio (dennisvonbargen.com)",
                            Role = "Full-stack .NET Developer",
                            Show = true,
                            StartDate = new DateTime(2020, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.ProjectSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProjectId = 2,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProjectId = 2,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 3,
                            ProjectId = 2,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 4,
                            ProjectId = 2,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 5,
                            ProjectId = 2,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 6,
                            ProjectId = 2,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 7,
                            ProjectId = 2,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 8,
                            ProjectId = 2,
                            SkillId = 9
                        },
                        new
                        {
                            Id = 9,
                            ProjectId = 2,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 10,
                            ProjectId = 2,
                            SkillId = 11
                        },
                        new
                        {
                            Id = 11,
                            ProjectId = 2,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 12,
                            ProjectId = 2,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 13,
                            ProjectId = 2,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 14,
                            ProjectId = 2,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 15,
                            ProjectId = 2,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 16,
                            ProjectId = 2,
                            SkillId = 17
                        },
                        new
                        {
                            Id = 17,
                            ProjectId = 2,
                            SkillId = 18
                        },
                        new
                        {
                            Id = 18,
                            ProjectId = 2,
                            SkillId = 19
                        },
                        new
                        {
                            Id = 19,
                            ProjectId = 3,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 20,
                            ProjectId = 3,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 21,
                            ProjectId = 3,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 22,
                            ProjectId = 3,
                            SkillId = 20
                        },
                        new
                        {
                            Id = 23,
                            ProjectId = 3,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 24,
                            ProjectId = 3,
                            SkillId = 21
                        },
                        new
                        {
                            Id = 25,
                            ProjectId = 3,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 26,
                            ProjectId = 3,
                            SkillId = 22
                        },
                        new
                        {
                            Id = 27,
                            ProjectId = 3,
                            SkillId = 23
                        },
                        new
                        {
                            Id = 28,
                            ProjectId = 3,
                            SkillId = 24
                        },
                        new
                        {
                            Id = 29,
                            ProjectId = 3,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 30,
                            ProjectId = 4,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 31,
                            ProjectId = 4,
                            SkillId = 13
                        },
                        new
                        {
                            Id = 32,
                            ProjectId = 4,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 33,
                            ProjectId = 4,
                            SkillId = 6
                        },
                        new
                        {
                            Id = 34,
                            ProjectId = 4,
                            SkillId = 16
                        },
                        new
                        {
                            Id = 35,
                            ProjectId = 4,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 36,
                            ProjectId = 4,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 37,
                            ProjectId = 4,
                            SkillId = 19
                        },
                        new
                        {
                            Id = 38,
                            ProjectId = 4,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 39,
                            ProjectId = 5,
                            SkillId = 25
                        },
                        new
                        {
                            Id = 40,
                            ProjectId = 5,
                            SkillId = 26
                        },
                        new
                        {
                            Id = 41,
                            ProjectId = 5,
                            SkillId = 27
                        },
                        new
                        {
                            Id = 42,
                            ProjectId = 6,
                            SkillId = 28
                        },
                        new
                        {
                            Id = 43,
                            ProjectId = 6,
                            SkillId = 1
                        },
                        new
                        {
                            Id = 44,
                            ProjectId = 6,
                            SkillId = 29
                        },
                        new
                        {
                            Id = 45,
                            ProjectId = 6,
                            SkillId = 30
                        },
                        new
                        {
                            Id = 46,
                            ProjectId = 6,
                            SkillId = 31
                        },
                        new
                        {
                            Id = 47,
                            ProjectId = 6,
                            SkillId = 32
                        },
                        new
                        {
                            Id = 48,
                            ProjectId = 6,
                            SkillId = 33
                        },
                        new
                        {
                            Id = 49,
                            ProjectId = 6,
                            SkillId = 34
                        },
                        new
                        {
                            Id = 50,
                            ProjectId = 7,
                            SkillId = 35
                        },
                        new
                        {
                            Id = 51,
                            ProjectId = 7,
                            SkillId = 36
                        },
                        new
                        {
                            Id = 52,
                            ProjectId = 7,
                            SkillId = 37
                        },
                        new
                        {
                            Id = 53,
                            ProjectId = 7,
                            SkillId = 27
                        },
                        new
                        {
                            Id = 54,
                            ProjectId = 7,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 55,
                            ProjectId = 7,
                            SkillId = 38
                        },
                        new
                        {
                            Id = 56,
                            ProjectId = 7,
                            SkillId = 39
                        },
                        new
                        {
                            Id = 57,
                            ProjectId = 7,
                            SkillId = 40
                        },
                        new
                        {
                            Id = 58,
                            ProjectId = 7,
                            SkillId = 41
                        },
                        new
                        {
                            Id = 59,
                            ProjectId = 7,
                            SkillId = 42
                        },
                        new
                        {
                            Id = 60,
                            ProjectId = 7,
                            SkillId = 43
                        },
                        new
                        {
                            Id = 61,
                            ProjectId = 7,
                            SkillId = 32
                        },
                        new
                        {
                            Id = 62,
                            ProjectId = 7,
                            SkillId = 44
                        },
                        new
                        {
                            Id = 63,
                            ProjectId = 7,
                            SkillId = 45
                        },
                        new
                        {
                            Id = 64,
                            ProjectId = 7,
                            SkillId = 46
                        },
                        new
                        {
                            Id = 65,
                            ProjectId = 7,
                            SkillId = 47
                        },
                        new
                        {
                            Id = 66,
                            ProjectId = 7,
                            SkillId = 48
                        },
                        new
                        {
                            Id = 67,
                            ProjectId = 7,
                            SkillId = 49
                        },
                        new
                        {
                            Id = 68,
                            ProjectId = 8,
                            SkillId = 47
                        },
                        new
                        {
                            Id = 69,
                            ProjectId = 8,
                            SkillId = 36
                        },
                        new
                        {
                            Id = 70,
                            ProjectId = 8,
                            SkillId = 50
                        },
                        new
                        {
                            Id = 71,
                            ProjectId = 8,
                            SkillId = 37
                        },
                        new
                        {
                            Id = 72,
                            ProjectId = 8,
                            SkillId = 27
                        },
                        new
                        {
                            Id = 73,
                            ProjectId = 10,
                            SkillId = 36
                        },
                        new
                        {
                            Id = 74,
                            ProjectId = 10,
                            SkillId = 27
                        },
                        new
                        {
                            Id = 75,
                            ProjectId = 10,
                            SkillId = 40
                        },
                        new
                        {
                            Id = 76,
                            ProjectId = 10,
                            SkillId = 42
                        },
                        new
                        {
                            Id = 77,
                            ProjectId = 10,
                            SkillId = 51
                        },
                        new
                        {
                            Id = 78,
                            ProjectId = 10,
                            SkillId = 43
                        },
                        new
                        {
                            Id = 79,
                            ProjectId = 10,
                            SkillId = 47
                        },
                        new
                        {
                            Id = 80,
                            ProjectId = 10,
                            SkillId = 52
                        },
                        new
                        {
                            Id = 81,
                            ProjectId = 10,
                            SkillId = 49
                        },
                        new
                        {
                            Id = 82,
                            ProjectId = 9,
                            SkillId = 35
                        },
                        new
                        {
                            Id = 83,
                            ProjectId = 9,
                            SkillId = 53
                        },
                        new
                        {
                            Id = 84,
                            ProjectId = 9,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 85,
                            ProjectId = 9,
                            SkillId = 38
                        },
                        new
                        {
                            Id = 86,
                            ProjectId = 9,
                            SkillId = 39
                        },
                        new
                        {
                            Id = 87,
                            ProjectId = 9,
                            SkillId = 54
                        },
                        new
                        {
                            Id = 88,
                            ProjectId = 9,
                            SkillId = 32
                        },
                        new
                        {
                            Id = 89,
                            ProjectId = 9,
                            SkillId = 44
                        },
                        new
                        {
                            Id = 90,
                            ProjectId = 9,
                            SkillId = 49
                        },
                        new
                        {
                            Id = 91,
                            ProjectId = 11,
                            SkillId = 53
                        },
                        new
                        {
                            Id = 92,
                            ProjectId = 11,
                            SkillId = 55
                        },
                        new
                        {
                            Id = 93,
                            ProjectId = 11,
                            SkillId = 56
                        },
                        new
                        {
                            Id = 94,
                            ProjectId = 11,
                            SkillId = 57
                        },
                        new
                        {
                            Id = 95,
                            ProjectId = 11,
                            SkillId = 58
                        },
                        new
                        {
                            Id = 96,
                            ProjectId = 11,
                            SkillId = 18
                        },
                        new
                        {
                            Id = 97,
                            ProjectId = 11,
                            SkillId = 59
                        },
                        new
                        {
                            Id = 98,
                            ProjectId = 11,
                            SkillId = 5
                        },
                        new
                        {
                            Id = 99,
                            ProjectId = 11,
                            SkillId = 61
                        },
                        new
                        {
                            Id = 100,
                            ProjectId = 11,
                            SkillId = 19
                        },
                        new
                        {
                            Id = 101,
                            ProjectId = 11,
                            SkillId = 60
                        },
                        new
                        {
                            Id = 102,
                            ProjectId = 12,
                            SkillId = 62
                        },
                        new
                        {
                            Id = 103,
                            ProjectId = 12,
                            SkillId = 11
                        },
                        new
                        {
                            Id = 104,
                            ProjectId = 12,
                            SkillId = 12
                        },
                        new
                        {
                            Id = 105,
                            ProjectId = 12,
                            SkillId = 63
                        },
                        new
                        {
                            Id = 106,
                            ProjectId = 12,
                            SkillId = 64
                        },
                        new
                        {
                            Id = 107,
                            ProjectId = 12,
                            SkillId = 36
                        },
                        new
                        {
                            Id = 108,
                            ProjectId = 12,
                            SkillId = 4
                        },
                        new
                        {
                            Id = 109,
                            ProjectId = 12,
                            SkillId = 55
                        },
                        new
                        {
                            Id = 110,
                            ProjectId = 12,
                            SkillId = 65
                        },
                        new
                        {
                            Id = 111,
                            ProjectId = 12,
                            SkillId = 66
                        },
                        new
                        {
                            Id = 112,
                            ProjectId = 12,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 113,
                            ProjectId = 12,
                            SkillId = 67
                        },
                        new
                        {
                            Id = 114,
                            ProjectId = 12,
                            SkillId = 3
                        },
                        new
                        {
                            Id = 115,
                            ProjectId = 12,
                            SkillId = 68
                        },
                        new
                        {
                            Id = 116,
                            ProjectId = 12,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 117,
                            ProjectId = 12,
                            SkillId = 17
                        },
                        new
                        {
                            Id = 118,
                            ProjectId = 12,
                            SkillId = 69
                        },
                        new
                        {
                            Id = 119,
                            ProjectId = 12,
                            SkillId = 70
                        },
                        new
                        {
                            Id = 120,
                            ProjectId = 12,
                            SkillId = 71
                        },
                        new
                        {
                            Id = 121,
                            ProjectId = 12,
                            SkillId = 72
                        },
                        new
                        {
                            Id = 122,
                            ProjectId = 12,
                            SkillId = 73
                        },
                        new
                        {
                            Id = 123,
                            ProjectId = 12,
                            SkillId = 74
                        },
                        new
                        {
                            Id = 124,
                            ProjectId = 12,
                            SkillId = 75
                        },
                        new
                        {
                            Id = 125,
                            ProjectId = 12,
                            SkillId = 76
                        },
                        new
                        {
                            Id = 126,
                            ProjectId = 12,
                            SkillId = 77
                        },
                        new
                        {
                            Id = 127,
                            ProjectId = 12,
                            SkillId = 78
                        },
                        new
                        {
                            Id = 128,
                            ProjectId = 13,
                            SkillId = 79
                        },
                        new
                        {
                            Id = 129,
                            ProjectId = 13,
                            SkillId = 80
                        },
                        new
                        {
                            Id = 130,
                            ProjectId = 13,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 131,
                            ProjectId = 13,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 132,
                            ProjectId = 13,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 133,
                            ProjectId = 13,
                            SkillId = 81
                        },
                        new
                        {
                            Id = 134,
                            ProjectId = 13,
                            SkillId = 21
                        },
                        new
                        {
                            Id = 135,
                            ProjectId = 13,
                            SkillId = 74
                        },
                        new
                        {
                            Id = 136,
                            ProjectId = 13,
                            SkillId = 31
                        },
                        new
                        {
                            Id = 137,
                            ProjectId = 13,
                            SkillId = 82
                        },
                        new
                        {
                            Id = 138,
                            ProjectId = 13,
                            SkillId = 83
                        },
                        new
                        {
                            Id = 139,
                            ProjectId = 13,
                            SkillId = 60
                        },
                        new
                        {
                            Id = 140,
                            ProjectId = 13,
                            SkillId = 84
                        },
                        new
                        {
                            Id = 141,
                            ProjectId = 13,
                            SkillId = 77
                        },
                        new
                        {
                            Id = 142,
                            ProjectId = 13,
                            SkillId = 85
                        },
                        new
                        {
                            Id = 143,
                            ProjectId = 14,
                            SkillId = 62
                        },
                        new
                        {
                            Id = 144,
                            ProjectId = 14,
                            SkillId = 53
                        },
                        new
                        {
                            Id = 145,
                            ProjectId = 14,
                            SkillId = 8
                        },
                        new
                        {
                            Id = 146,
                            ProjectId = 14,
                            SkillId = 36
                        },
                        new
                        {
                            Id = 147,
                            ProjectId = 14,
                            SkillId = 55
                        },
                        new
                        {
                            Id = 148,
                            ProjectId = 14,
                            SkillId = 86
                        },
                        new
                        {
                            Id = 149,
                            ProjectId = 14,
                            SkillId = 66
                        },
                        new
                        {
                            Id = 150,
                            ProjectId = 14,
                            SkillId = 87
                        },
                        new
                        {
                            Id = 151,
                            ProjectId = 14,
                            SkillId = 88
                        },
                        new
                        {
                            Id = 152,
                            ProjectId = 14,
                            SkillId = 10
                        },
                        new
                        {
                            Id = 153,
                            ProjectId = 14,
                            SkillId = 2
                        },
                        new
                        {
                            Id = 154,
                            ProjectId = 14,
                            SkillId = 61
                        },
                        new
                        {
                            Id = 155,
                            ProjectId = 14,
                            SkillId = 89
                        },
                        new
                        {
                            Id = 156,
                            ProjectId = 14,
                            SkillId = 90
                        },
                        new
                        {
                            Id = 157,
                            ProjectId = 14,
                            SkillId = 91
                        },
                        new
                        {
                            Id = 158,
                            ProjectId = 14,
                            SkillId = 20
                        },
                        new
                        {
                            Id = 159,
                            ProjectId = 14,
                            SkillId = 92
                        },
                        new
                        {
                            Id = 160,
                            ProjectId = 14,
                            SkillId = 93
                        },
                        new
                        {
                            Id = 161,
                            ProjectId = 14,
                            SkillId = 60
                        },
                        new
                        {
                            Id = 162,
                            ProjectId = 14,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 163,
                            ProjectId = 14,
                            SkillId = 47
                        },
                        new
                        {
                            Id = 164,
                            ProjectId = 14,
                            SkillId = 94
                        },
                        new
                        {
                            Id = 165,
                            ProjectId = 14,
                            SkillId = 78
                        },
                        new
                        {
                            Id = 166,
                            ProjectId = 15,
                            SkillId = 62
                        },
                        new
                        {
                            Id = 167,
                            ProjectId = 15,
                            SkillId = 79
                        },
                        new
                        {
                            Id = 168,
                            ProjectId = 15,
                            SkillId = 80
                        },
                        new
                        {
                            Id = 169,
                            ProjectId = 15,
                            SkillId = 95
                        },
                        new
                        {
                            Id = 170,
                            ProjectId = 15,
                            SkillId = 96
                        },
                        new
                        {
                            Id = 171,
                            ProjectId = 15,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 172,
                            ProjectId = 15,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 173,
                            ProjectId = 15,
                            SkillId = 97
                        },
                        new
                        {
                            Id = 174,
                            ProjectId = 15,
                            SkillId = 74
                        },
                        new
                        {
                            Id = 175,
                            ProjectId = 15,
                            SkillId = 84
                        },
                        new
                        {
                            Id = 176,
                            ProjectId = 15,
                            SkillId = 85
                        },
                        new
                        {
                            Id = 177,
                            ProjectId = 16,
                            SkillId = 98
                        },
                        new
                        {
                            Id = 178,
                            ProjectId = 16,
                            SkillId = 100
                        },
                        new
                        {
                            Id = 179,
                            ProjectId = 16,
                            SkillId = 56
                        },
                        new
                        {
                            Id = 180,
                            ProjectId = 16,
                            SkillId = 55
                        },
                        new
                        {
                            Id = 181,
                            ProjectId = 16,
                            SkillId = 86
                        },
                        new
                        {
                            Id = 182,
                            ProjectId = 16,
                            SkillId = 71
                        },
                        new
                        {
                            Id = 183,
                            ProjectId = 16,
                            SkillId = 75
                        },
                        new
                        {
                            Id = 184,
                            ProjectId = 16,
                            SkillId = 76
                        },
                        new
                        {
                            Id = 185,
                            ProjectId = 16,
                            SkillId = 78
                        },
                        new
                        {
                            Id = 186,
                            ProjectId = 17,
                            SkillId = 62
                        },
                        new
                        {
                            Id = 187,
                            ProjectId = 17,
                            SkillId = 100
                        },
                        new
                        {
                            Id = 188,
                            ProjectId = 17,
                            SkillId = 36
                        },
                        new
                        {
                            Id = 189,
                            ProjectId = 17,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 190,
                            ProjectId = 17,
                            SkillId = 67
                        },
                        new
                        {
                            Id = 191,
                            ProjectId = 17,
                            SkillId = 103
                        },
                        new
                        {
                            Id = 192,
                            ProjectId = 17,
                            SkillId = 101
                        },
                        new
                        {
                            Id = 193,
                            ProjectId = 17,
                            SkillId = 32
                        },
                        new
                        {
                            Id = 194,
                            ProjectId = 17,
                            SkillId = 75
                        },
                        new
                        {
                            Id = 195,
                            ProjectId = 17,
                            SkillId = 102
                        },
                        new
                        {
                            Id = 196,
                            ProjectId = 17,
                            SkillId = 104
                        },
                        new
                        {
                            Id = 197,
                            ProjectId = 17,
                            SkillId = 76
                        },
                        new
                        {
                            Id = 198,
                            ProjectId = 16,
                            SkillId = 99
                        },
                        new
                        {
                            Id = 199,
                            ProjectId = 18,
                            SkillId = 62
                        },
                        new
                        {
                            Id = 200,
                            ProjectId = 18,
                            SkillId = 104
                        },
                        new
                        {
                            Id = 201,
                            ProjectId = 18,
                            SkillId = 90
                        },
                        new
                        {
                            Id = 202,
                            ProjectId = 18,
                            SkillId = 105
                        },
                        new
                        {
                            Id = 203,
                            ProjectId = 18,
                            SkillId = 106
                        },
                        new
                        {
                            Id = 204,
                            ProjectId = 18,
                            SkillId = 107
                        },
                        new
                        {
                            Id = 205,
                            ProjectId = 18,
                            SkillId = 108
                        },
                        new
                        {
                            Id = 206,
                            ProjectId = 18,
                            SkillId = 109
                        },
                        new
                        {
                            Id = 207,
                            ProjectId = 18,
                            SkillId = 110
                        },
                        new
                        {
                            Id = 208,
                            ProjectId = 18,
                            SkillId = 55
                        },
                        new
                        {
                            Id = 209,
                            ProjectId = 18,
                            SkillId = 7
                        },
                        new
                        {
                            Id = 210,
                            ProjectId = 18,
                            SkillId = 111
                        },
                        new
                        {
                            Id = 211,
                            ProjectId = 18,
                            SkillId = 112
                        },
                        new
                        {
                            Id = 212,
                            ProjectId = 18,
                            SkillId = 86
                        },
                        new
                        {
                            Id = 213,
                            ProjectId = 18,
                            SkillId = 66
                        },
                        new
                        {
                            Id = 214,
                            ProjectId = 18,
                            SkillId = 71
                        },
                        new
                        {
                            Id = 215,
                            ProjectId = 18,
                            SkillId = 14
                        },
                        new
                        {
                            Id = 216,
                            ProjectId = 18,
                            SkillId = 67
                        },
                        new
                        {
                            Id = 217,
                            ProjectId = 18,
                            SkillId = 15
                        },
                        new
                        {
                            Id = 218,
                            ProjectId = 18,
                            SkillId = 58
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JavaEE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Linux"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 4,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 5,
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 6,
                            Name = "GlassFish"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ubuntu"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bash"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SSH"
                        },
                        new
                        {
                            Id = 10,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 11,
                            Name = "AJAX"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Atlassian Jira"
                        },
                        new
                        {
                            Id = 13,
                            Name = "EJB (Enterprise JavaBeans)"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 15,
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 16,
                            Name = "JDBC"
                        },
                        new
                        {
                            Id = 17,
                            Name = "jQuery"
                        },
                        new
                        {
                            Id = 18,
                            Name = "JSON"
                        },
                        new
                        {
                            Id = 19,
                            Name = "SQL"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Shell script"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 22,
                            Name = "NGINX"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Backup & restore"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Cron"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Defold Engine"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lua"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Game design"
                        },
                        new
                        {
                            Id = 28,
                            Name = "JUnit"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Oracle Database"
                        },
                        new
                        {
                            Id = 30,
                            Name = "SVN"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Selenium"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Scrum"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Automated UI testing"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Jenkins"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Agile development"
                        },
                        new
                        {
                            Id = 36,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 37,
                            Name = "FMOD"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Git LFS"
                        },
                        new
                        {
                            Id = 39,
                            Name = "GitLab"
                        },
                        new
                        {
                            Id = 40,
                            Name = "HTC Vive"
                        },
                        new
                        {
                            Id = 41,
                            Name = "NewtonVR"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Oculus Rift"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Prototyping"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Sourcetree"
                        },
                        new
                        {
                            Id = 45,
                            Name = "SteamVR"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Steamworks"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Unity3D"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Viveport"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            Id = 50,
                            Name = "FL Studio"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Project management"
                        },
                        new
                        {
                            Id = 52,
                            Name = "VRTK"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Amazon Web Services (AWS)"
                        },
                        new
                        {
                            Id = 54,
                            Name = "REST API"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Unit testing"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Batch script"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Chai.js"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Database modeling"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Mocha"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Test Driven Development (TDD)"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 62,
                            Name = ".NET Core"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Atlassian Confluence"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Entity Framework (EF)"
                        },
                        new
                        {
                            Id = 66,
                            Name = "FluentAssertions"
                        },
                        new
                        {
                            Id = 67,
                            Name = "GitExtensions"
                        },
                        new
                        {
                            Id = 68,
                            Name = "gulp.js"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Less"
                        },
                        new
                        {
                            Id = 70,
                            Name = "LINQ"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Microsoft Visual Studio"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Model-view-controller (MVC)"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Razor (HTML5)"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Regular expressions"
                        },
                        new
                        {
                            Id = 75,
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 76,
                            Name = "T-SQL"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Unified Modeling Language (UML)"
                        },
                        new
                        {
                            Id = 78,
                            Name = "xUnit"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Stocks"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Stock analysis"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Pycharm"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Synology"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Synology DSM"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Value investment"
                        },
                        new
                        {
                            Id = 85,
                            Name = "XPath"
                        },
                        new
                        {
                            Id = 86,
                            Name = "FakeItEasy"
                        },
                        new
                        {
                            Id = 87,
                            Name = "HashiCorp Terraform"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Infrastructure as Code (IaC)"
                        },
                        new
                        {
                            Id = 89,
                            Name = "OS X"
                        },
                        new
                        {
                            Id = 90,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 91,
                            Name = "React.js"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Rider"
                        },
                        new
                        {
                            Id = 93,
                            Name = "TeamCity"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Unix"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Azure Functions"
                        },
                        new
                        {
                            Id = 96,
                            Name = "curl"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Microsoft Excel"
                        },
                        new
                        {
                            Id = 98,
                            Name = ".NET Framework"
                        },
                        new
                        {
                            Id = 99,
                            Name = "WebForms"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Azure DevOps"
                        },
                        new
                        {
                            Id = 101,
                            Name = "React Router"
                        },
                        new
                        {
                            Id = 102,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 103,
                            Name = "React Hooks"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Entity Framework Core (EF Core)"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Docker Compose"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Docker Hub"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Digital Ocean"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Automated Builds"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Blazor"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Component-based UI Design"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Domain name administration"
                        });
                });

            modelBuilder.Entity("Portfolio.Core.Entities.Project", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Employer", "Employer")
                        .WithMany("Projects")
                        .HasForeignKey("EmployerId");
                });

            modelBuilder.Entity("Portfolio.Core.Entities.ProjectSkill", b =>
                {
                    b.HasOne("Portfolio.Core.Entities.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portfolio.Core.Entities.Skill", "Skill")
                        .WithMany("ProjectTechnologies")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
